auth:
  wx:
    domain: https://open.weixin.qq.com
    silenceScope: snsapi_base
    silenceNo: snsapi_userinfo
    requestCode: ${auth.wx.domain}/connect/oauth2/authorize?appid=${wx.validate.appId}&redirect_uri=
    code2AuthAccessToken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${wx.validate.appId}&secret=${wx.validate.appSecret}&grant_type=authorization_code&code=
