wx:
  url:
    redirect_uri: http://
  public_number:
    # 与微信公众号后台中: 开发->基本配置->公众号开发信息->开发者ID(AppID)保持一致
    app_id: wxc050ff4a4f9470f9
    # 与微信公众号后台中: 开发->基本配置->公众号开发信息->开发者密码(AppSecret)保持一致
    app_secret: cf842d72bdb06d91095a207506a6146c
    # 与微信公众号后台中: 开发->基本配置->服务器配置->令牌(Token)保持一致
    config_token: developer_home
service:
  package: org.yyx.wx.serviceimpl
  # 处理器方式 现只支持 customer all default
  handler_type: all
swagger:
  enable: true