cjwy:
  wechat:
    publicnum:
      credential:
        accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wx.pubnum.appid}&secret=${wx.pubnum.secret}
      oauth2:
        code: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${wx.pubnum.appid}
        webViewAccessToken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${wx.pubnum.appid}&secret=${wx.pubnum.secret}&grant_type=authorization_code&code=
        refreshToken: https://api.weixin.qq.com/sns/oauth2/refresh_token?appid=${wx.pubnum.appid}&grant_type=refresh_token&refresh_token=
        userInfo: https://api.weixin.qq.com/sns/userinfo?lang=${wx.pubnum.lang}&access_token=
        checkAccessToken: https://api.weixin.qq.com/sns/auth?access_token=
      userInfo:
        baseUserInfo: https://api.weixin.qq.com/cgi-bin/user/info?access_token=
        batchUserInfo: https://api.weixin.qq.com/cgi-bin/user/info/batchget?access_token=
      qrCode:
        ticket: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=
        generateImage: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=